### ISSUE TITLE
Window size has problem on 4K display.

### ISSUE THREAD

**Issue by raytions** [Tatsu-syo/ReMetrics#1]
![image](https://user-images.githubusercontent.com/12690775/82737067-05368a80-9d26-11ea-8b26-74d680f8688c.png)

It not able to change the window size, and some functions below are hidden.

Windows 10 1809/ Dell 4K display

**Comment by Tatsu-syo** [comment]
@Cineray 
I'm sorry to response too late.
When I make version 1.30, I don't HiDpi.
I make test version.
Please try it.

[DPItest.zip](https://github.com/Tatsu-syo/ReMetrics/files/4809075/DPItest.zip)

**Comment by raytions** [comment]
Thank you, This one looks better, But still a little bit crop.
![image](https://user-images.githubusercontent.com/12690775/85868512-49ec9000-b7c2-11ea-905c-1c0a8a5e1ed4.png)
Thank you for your reply.

**Comment by Tatsu-syo** [comment]
@Cineray
I'm sorry to response too late.
I make test version.
Window size is adjusted.
Please try it.
[ReMetrics131test.zip](https://github.com/Tatsu-syo/ReMetrics/files/4874602/ReMetrics131test.zip)

**Comment by raytions** [comment]
This version is perfect in my 4K display.
Thank you!

**Comment by raytions** [comment]
By the way, it would be nice if make UI font larger.
![image](https://user-images.githubusercontent.com/12690775/86548370-074e5480-bf34-11ea-9392-5a42712c5d33.png)

**Comment by Tatsu-syo** [comment]
@Cineray It's font issue. Previous version I use "System" font in English.
This test version, I use "Courie New". Font size grows on system DPI.
In English, what font is used in commonly?
Please tell me commonly used font.
Thank you.
[ReMetrics131test3.zip](https://github.com/Tatsu-syo/ReMetrics/files/4908176/ReMetrics131test3.zip)

**Comment by Tatsu-syo** [comment]
@Cineray Ah, Re-Metrics runs Windows Vista and later.
So, We can use Segoe UI.
Attach Segoe UI version sample. How about it?
[ReMetrics131test4.zip](https://github.com/Tatsu-syo/ReMetrics/files/4908369/ReMetrics131test4.zip)

**Comment by raytions** [comment]
Perfect!

![Untitled](https://user-images.githubusercontent.com/12690775/87855269-fd9ef680-c90e-11ea-955c-6a76b67ec695.jpg)

Thank you!!!

**Comment by Tatsu-syo** [comment]
@Cineray 
Thank you for your coopration.
I release new version of Re-Metrics.

Close this issue.
